apiVersion: 1

contactPoints:
  - orgId: 1
    name: fe-radar-dingtalk
    receivers:
      - uid: fe-radar-dingtalk
        type: dingding
        disableResolveMessage: false
        settings:
          url: $GRAFANA_DINGTALK_WEBHOOK_URL
          msgType: link
          message: |
            {{ template "default.message" . }}

policies:
  - orgId: 1
    receiver: fe-radar-dingtalk
    group_by: ["grafana_folder", "alertname"]
    group_wait: 30s
    group_interval: 5m
    repeat_interval: 4h
